### PR TITLE
Added README.md

### PR DESCRIPTION
**Pull request by ubikusss**

### CODE REVIEW

**Comment by ubikusss** [comment]
@cosmyo - would you take a look?

**Comment by cosmyo** [comment]
Yes, please add me as a reviewer next time. Otherwise, I am not aware a pr has been raised.

**Comment by ubikusss** [comment]
> Yes, please add me as a reviewer next time. Otherwise, I am not aware a pr has been raised.

I cannot add reviewers.

**Comment by ubikusss** [comment]
@cosminvlad - please check and approve is possible, customers are looking for docs on CCP.

**Review by cosminvlad — APPROVED** [review]

**Pull request merged**
